table metaDomainClinVar
"MetaDome: pathogenic ClinVar variation projected through Pfam domain alignments. Each feature is a codon inside a Pfam domain that has at least one Pathogenic or Likely pathogenic ClinVar variant at the evolutionarily equivalent position in another gene."
    (
    string  chrom;              "Reference sequence chromosome"
    uint    chromStart;         "Start position of the codon"
    uint    chromEnd;           "End position of the codon"
    string  name;               "UniProt accession/position : Pfam ID : domain consensus position"
    uint    score;              "Homologous P+LP count, scaled to 0-1000 for shading"
    char[1] strand;             "Strand of the reading frame"
    uint    thickStart;         "Start of thick drawing (same as chromStart)"
    uint    thickEnd;           "End of thick drawing (same as chromEnd)"
    uint    itemRgb;            "Red where Pathogenic dominates, orange where Likely pathogenic does"
    string  uniprot_ac;         "UniProtKB/Swiss-Prot accession, isoform-suffixed where applicable"
    uint    uniprot_pos;        "Residue position, 1-based from the initiator methionine"
    string  pfam_id;            "Pfam domain accession"
    uint    consensus_pos;      "Position in the Pfam domain consensus; equal positions across genes are evolutionarily equivalent"
    uint    homolog_P_count;    "Pathogenic ClinVar variants at this consensus position in other genes"
    uint    homolog_LP_count;   "Likely pathogenic ClinVar variants at this consensus position in other genes"
    uint    homolog_P_missense_count;   "Of homolog_P_count, those that are missense"
    uint    homolog_LP_missense_count;  "Of homolog_LP_count, those that are missense"
    lstring meta_domain_clinvar_P_records;   "Comma-separated ClinVar accessions counted in homolog_P_count"
    lstring meta_domain_clinvar_LP_records;  "Comma-separated ClinVar accessions counted in homolog_LP_count"
    lstring metadome_url;       "Link to this genomic position in MetaDome"
    )
